resources
| where  subscriptionId =="xxxxxxxxxxxxxxxx"
| where type =~ 'Microsoft.Sql/servers'
| project id, name, resourceGroup, location, FQDN= tostring(properties.fullyQualifiedDomainName), pricingTier = tostring(properties.sku.tier), PublicAccess=tostring(properties.publicNetworkAccess), PrivateEndpoint=split(properties.privateEndpointConnections[0].properties.privateEndpoint.id, '/')[-1], properties
